### ISSUE TITLE
Some sensor.* missing from LTSS

### ISSUE THREAD

**Issue by phlundblom** [freol35241/ltss#248]
Thanks for a great component!

I have been using LTSS for about a year and just recently noticed that some entities that should be covered by the `sensor` domain include in min configuration isn't logged to TimescaleDB. I cannot really find any obvious patterns such as the same unit or similar. The behavior can be noticed when looking at historic values in HA. For LTSS-logged sensors there is historic data, for the ones missing it there is only Recorder data from the last 10 days.

Not sure where to start debugging this though. Sensors missing from LTSS is both real entities (ESPHome) and calculated (Helpers/Templates).

My configuration block from `configuration.yaml`. An example of a sensor missing from the LTSS data is `sensor.anemometer_vindhastighet_by`.

```
ltss:
  db_url: !secret psql_string
  chunk_time_interval: 2592000000000
  include:
    domains:
      - sensor
      - climate
    entities:
      - binary_sensor.sune
      - binary_sensor.tvattstugan_connectivity
  exclude:
    entities:
      - sensor.uppfarten_car_count
      - sensor.hela_uppfarten_person_count
      - sensor.uppfarten_bicycle_count
      - sensor.biluppfarten_truck_count
      - sensor.uppfarten_person_count
      - sensor.biluppfarten_car_count
      - sensor.hela_uppfarten_motorcycle_count
      - sensor.hela_uppfarten_bicycle_count
      - sensor.uppfarten_all_count
      - sensor.hela_uppfarten_cat_count
      - sensor.hela_uppfarten_all_count
      - sensor.uppfarten_motorcycle_count
      - sensor.uppfarten_cat_count
      - sensor.biluppfarten_all_count
      - sensor.uppfarten_truck_count
      - sensor.hp_laserjet_500_color_m551
      - sensor.hp_laserjet_500_color_m551_black_cartridge
      - sensor.hp_laserjet_500_color_m551_cyan_cartridge
      - sensor.hp_laserjet_500_color_m551_fuser_kit
      - sensor.hp_laserjet_500_color_m551_magenta_cartridge
      - sensor.hp_laserjet_500_color_m551_yellow_cartridge
```

Any ideas or hints on where I should start troubleshooting this?
