### ISSUE TITLE
exclude not applied?

### ISSUE THREAD

**Issue by michalk-k** [freol35241/ltss#252]
Here is my ltss config:

```yaml
ltss:
  db_url: postgresql://ha:ha@77b2833f-timescaledb/ha_timescale
  chunk_time_interval: 2592000000000
  include:
    entities:
      - sensor.glances_cpu_load
      - sensor.glances_cpu_used
      - sensor.glances_cpu_percent
      - sensor.glances_cpu_thermal_0_temperature
      - sensor.glances_ram_free
      - sensor.glances_ram_used
      - sensor.glances_ram_used_percent
      - sensor.glances_swap_free
      - sensor.glances_swap_used
      - sensor.glances_data_free
      - sensor.glances_swap_used
      - sensor.glances_data_used_percent
    entity_globs:
      - sensor.wattsonic*
      - sensor.*energy
      - sensor.*power
      - sensor.*temperature
      - sensor.*memory_percent
      - sensor.*cpu_percent
      - sensor.*memory_percent
  exclude:
    entity_globs:
      - sensor.shelly_3em_cube*
  ```

The `include` adds sensors matching `sensor.*power` which matches many sensors. I would like to exclude a few from this bunch, thus excluding `sensor.shelly_3em_cube*`

Unfortunately following sensors are still being stored to timescaleDB:
 * sensor.shelly_3em_cube_phase_3_power
 * sensor.shelly_3em_cube_phase_1_power
 * sensor.shelly_3em_cube_phase_2_power
