### ISSUE TITLE
unknown not published

### ISSUE THREAD

**Issue by michal-bartak** [freol35241/ltss#272]
Hello.
I found that the sensor that changes state from `unavailable` to `unknown` is not published to TimescaleDB.
Not sure it's about the transition between those 2 particular states, or the fact that the new state is `unknown`. Or maybe something else?

Can you confirm that it's possible and expected?

The sensor is created and maintained by another [custom component](https://github.com/rnovacek/homeassistant_cz_energy_spot_prices). This sensor provides the prices of electricity for the next day. The data are stored in attributes, while the state is set to `unknown` since it delivers no information. 

with regards

![Image](https://github.com/user-attachments/assets/f3e93750-2f64-4fe9-9453-1cd157e33387)

ltss config

```
ltss:
  db_url: postgresql://ha:ha@77b2833f-timescaledb/ha_timescale
  chunk_time_interval: 2592000000000
  include:
    entities:
      - sensor.glances_cpu_load
      - sensor.glances_cpu_used
      - sensor.glances_cpu_percent
      - sensor.glances_cpu_thermal_0_temperature
      - sensor.glances_ram_free
      - sensor.glances_ram_used
      - sensor.glances_ram_used_percent
      - sensor.glances_swap_free
      - sensor.glances_swap_used
      - sensor.glances_data_free
      - sensor.glances_swap_used
      - sensor.glances_data_used_percent
      - sensor.localhost_sda_disk_read
      - sensor.localhost_sda_disk_write
      - sensor.tomorrow_spot_electricity_hour_order
    entity_globs:
      - sensor.wattsonic*
      - sensor.*energy
      - sensor.*power
      - sensor.*temperature
      - sensor.*humidity
      - sensor.*memory_percent
      - sensor.*cpu_percent
      - sensor.*memory_percent
      - sensor.*_quarter_hourly
      - sensor.*_hourly
      - sensor.*_daily
  exclude:
    entity_globs:
      - sensor.shelly_3em_cube*
```
