### ISSUE TITLE
ltss won't load after update to ha-core 2023.3.2

### ISSUE THREAD

**Issue by agittins** [freol35241/ltss#56]
I'm running supervised on KVM, and timeseriesdb in a container outside of that VM, all of which has been running well for months.

I just updated from ha core 2023.2.something to 2023.3.2, using the web-ui.

I got errors at that point about not being able to satisfy the requirement for sqlalchemy >=1 and <2, so I updated ltss then from v1.x.x to the current release 2.0.1.

After rebooting the full VM, I get a notification that the ltss config is invalid:
![image](https://user-images.githubusercontent.com/752405/224023855-8b008998-aca0-42fb-8512-128e1fbf2e0f.png)

And the logs show this error:
```
Logger: homeassistant.setup
Source: setup.py:213
First occurred: 23:19:59 (1 occurrences)
Last logged: 23:19:59

Setup failed for custom integration ltss: Unable to import component: cannot import name 'with_metaclass' from 'sqlalchemy.util' (/usr/local/lib/python3.10/site-packages/sqlalchemy/util/__init__.py)
```

I tried (through the hacs gui) deleting and then downloading the ltss package again, but with the same result.

The docker container that supervisor is running for homeassistant is `74baa42900dd   ghcr.io/home-assistant/qemux86-64-homeassistant:2023.3.2` and running `python --version` in it reports `Python 3.10.10`. 

If I also run `pip show sqlalchemy` in that same container, I get:
```
# pip show sqlalchemy
Name: SQLAlchemy
Version: 2.0.5.post1
Summary: Database Abstraction Library
Home-page: https://www.sqlalchemy.org
Author: Mike Bayer
Author-email: mike_mp@zzzcomputing.com
License: MIT
Location: /usr/local/lib/python3.10/site-packages
Requires: greenlet, typing-extensions
Required-by: GeoAlchemy2, pygtfs
```

My `configuration.yaml` contains:
```
# AJG 2022-07-04 Now using PostgreSQL and TimescaleDB for history etc
recorder:                                                            
  db_url: !secret postgres_url                                       
ltss:                                                                
  db_url: !secret postgres_url                                       
  chunk_time_interval: 2592000000000                                 
```
(the `chunk_time_interval` was added today after the update to 2.0.1 and reading the new readme).

I couldn't see any issues searching the sqlalchemy tracker for with_metaclass, so I'm not really sure where to go from here. Any pointers to help work out what's happening?
